language: python
python:
- '2.7'
cache:
  directories:
  - "~/.platformio"
env:
- PLATFORMIO_CI_SRC=src/main.cpp
install:
- pip install -U platformio
script:
- platformio ci --project-conf=platformio.ini
deploy:
  provider: releases
  api_key:
    secure: pQoxs7OEWFT+opb8d7s4VO08/mgNg3G8BOoveXbK//XPXIEmOhulqLTeGuU7bEJdM2021N6t07V/pRVUvyp/2Doqnld5u7qgpZLw1BAcQ4Em/qcLca7eMFSe0vnecFZK/kbtwhU1mq2bAeK0cOhZhej6yOQv3N1tnxwoc9ICqjPdWNFtIEQ4cUJSB7ChFN5nrgrvRrPBqqFwN9p20ePZ2vTb/dSf2UoKvqn93+phiDGPPQ5K2daCSqbBruXMPiYkELGVnrCUxo2gO6iF18cnb+rLzg0pTZ8+EQLDua2Yreq97s5GcCUPU1/S/Sup2wfC8/VSbft3jtqjwyIiNpTiRWQyNp8WaAildOTb6wkSrSC0rQew8VKg2YK5nxCXFyZR3KB+LyErG98su+67IX4nhA9V0p1N9rzfKyQ1zTFXqYMG+KVseicvgXf9tj5jCbjA3lFNoFu1GHQ8RHHNmC9UUGN7ouI0RfKoIMcK4SpMzA4iJysI/fjCxUHTB945Wv4Wo4avi+Oq9X7Rw/hLZTpHEIWhpb7YVGcFfwQOdAAWgluZERFoNrX8zW2PNCxodppeTp0ABlt+HuVaTOlfPONa8EPZZSpmXMuP07KOg/5JNL/hnpywDTFfl12J2vc06UQvgmUwDJXWJ4Azw4YEBC4b0zjflDo1yFQR7nm6LF4xWQk=
  file:
  - ".pioenvs/esp-wrover-kit/firmware.bin"
  - ".pioenvs/esp-wrover-kit/firmware.elf"
  overwrite: true
  skip_cleanup: true
  on:
    repo: matt-g-everett/ledrx
    branches:
      only:
        - master
