language: python
python:
    - "2.7"

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/main.cpp

install:
    - pip install -U platformio

script:
    - platformio ci --board=esp-wrover-kit
