/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: coapapi.proto */

#ifndef PROTOBUF_C_coapapi_2eproto__INCLUDED
#define PROTOBUF_C_coapapi_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ledapi__Frame Ledapi__Frame;
typedef struct _Ledapi__ClassicConfig Ledapi__ClassicConfig;
typedef struct _Ledapi__ScanConfig Ledapi__ScanConfig;
typedef struct _Ledapi__Config Ledapi__Config;
typedef struct _Ledapi__FrameSet Ledapi__FrameSet;


/* --- enums --- */

typedef enum _Ledapi__ScanConfig__ScanMode {
  LEDAPI__SCAN_CONFIG__SCAN_MODE__WRAP = 0,
  LEDAPI__SCAN_CONFIG__SCAN_MODE__SWISH = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LEDAPI__SCAN_CONFIG__SCAN_MODE)
} Ledapi__ScanConfig__ScanMode;
typedef enum _Ledapi__ScanConfig__Direction {
  LEDAPI__SCAN_CONFIG__DIRECTION__DOWN = 0,
  LEDAPI__SCAN_CONFIG__DIRECTION__UP = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LEDAPI__SCAN_CONFIG__DIRECTION)
} Ledapi__ScanConfig__Direction;
typedef enum _Ledapi__Config__Mode {
  LEDAPI__CONFIG__MODE__OFF = 0,
  LEDAPI__CONFIG__MODE__FIXED_FRAME = 1,
  LEDAPI__CONFIG__MODE__PRESET = 2,
  LEDAPI__CONFIG__MODE__SCAN = 3,
  LEDAPI__CONFIG__MODE__CLASSIC = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LEDAPI__CONFIG__MODE)
} Ledapi__Config__Mode;
typedef enum _Ledapi__Config__Preset {
  LEDAPI__CONFIG__PRESET__NONE = 0,
  LEDAPI__CONFIG__PRESET__NIGHT = 1,
  LEDAPI__CONFIG__PRESET__CLASSIC_TREE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LEDAPI__CONFIG__PRESET)
} Ledapi__Config__Preset;

/* --- messages --- */

struct  _Ledapi__Frame
{
  ProtobufCMessage base;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
};
#define LEDAPI__FRAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledapi__frame__descriptor) \
    , 0,{0,NULL} }


struct  _Ledapi__ClassicConfig
{
  ProtobufCMessage base;
  protobuf_c_boolean has_num_highlights;
  uint32_t num_highlights;
  protobuf_c_boolean has_background_rgb;
  uint32_t background_rgb;
  protobuf_c_boolean has_highlight_rgb;
  uint32_t highlight_rgb;
  protobuf_c_boolean has_star_rgb;
  uint32_t star_rgb;
  protobuf_c_boolean has_num_twinkles;
  uint32_t num_twinkles;
  protobuf_c_boolean has_twinkle_rgb;
  uint32_t twinkle_rgb;
};
#define LEDAPI__CLASSIC_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledapi__classic_config__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0 }


struct  _Ledapi__ScanConfig
{
  ProtobufCMessage base;
  protobuf_c_boolean has_mode;
  Ledapi__ScanConfig__ScanMode mode;
  protobuf_c_boolean has_intensity;
  uint32_t intensity;
  protobuf_c_boolean has_trail_length;
  uint32_t trail_length;
  protobuf_c_boolean has_direction;
  Ledapi__ScanConfig__Direction direction;
};
#define LEDAPI__SCAN_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledapi__scan_config__descriptor) \
    , 0,0, 0,0, 0,0, 0,0 }


struct  _Ledapi__Config
{
  ProtobufCMessage base;
  protobuf_c_boolean has_mode;
  Ledapi__Config__Mode mode;
  protobuf_c_boolean has_preset;
  Ledapi__Config__Preset preset;
  Ledapi__Frame *frame;
  Ledapi__ClassicConfig *classic_config;
  Ledapi__ScanConfig *scan_config;
};
#define LEDAPI__CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledapi__config__descriptor) \
    , 0,0, 0,0, NULL, NULL, NULL }


struct  _Ledapi__FrameSet
{
  ProtobufCMessage base;
  size_t n_frames;
  Ledapi__Frame **frames;
};
#define LEDAPI__FRAME_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledapi__frame_set__descriptor) \
    , 0,NULL }


/* Ledapi__Frame methods */
void   ledapi__frame__init
                     (Ledapi__Frame         *message);
size_t ledapi__frame__get_packed_size
                     (const Ledapi__Frame   *message);
size_t ledapi__frame__pack
                     (const Ledapi__Frame   *message,
                      uint8_t             *out);
size_t ledapi__frame__pack_to_buffer
                     (const Ledapi__Frame   *message,
                      ProtobufCBuffer     *buffer);
Ledapi__Frame *
       ledapi__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledapi__frame__free_unpacked
                     (Ledapi__Frame *message,
                      ProtobufCAllocator *allocator);
/* Ledapi__ClassicConfig methods */
void   ledapi__classic_config__init
                     (Ledapi__ClassicConfig         *message);
size_t ledapi__classic_config__get_packed_size
                     (const Ledapi__ClassicConfig   *message);
size_t ledapi__classic_config__pack
                     (const Ledapi__ClassicConfig   *message,
                      uint8_t             *out);
size_t ledapi__classic_config__pack_to_buffer
                     (const Ledapi__ClassicConfig   *message,
                      ProtobufCBuffer     *buffer);
Ledapi__ClassicConfig *
       ledapi__classic_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledapi__classic_config__free_unpacked
                     (Ledapi__ClassicConfig *message,
                      ProtobufCAllocator *allocator);
/* Ledapi__ScanConfig methods */
void   ledapi__scan_config__init
                     (Ledapi__ScanConfig         *message);
size_t ledapi__scan_config__get_packed_size
                     (const Ledapi__ScanConfig   *message);
size_t ledapi__scan_config__pack
                     (const Ledapi__ScanConfig   *message,
                      uint8_t             *out);
size_t ledapi__scan_config__pack_to_buffer
                     (const Ledapi__ScanConfig   *message,
                      ProtobufCBuffer     *buffer);
Ledapi__ScanConfig *
       ledapi__scan_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledapi__scan_config__free_unpacked
                     (Ledapi__ScanConfig *message,
                      ProtobufCAllocator *allocator);
/* Ledapi__Config methods */
void   ledapi__config__init
                     (Ledapi__Config         *message);
size_t ledapi__config__get_packed_size
                     (const Ledapi__Config   *message);
size_t ledapi__config__pack
                     (const Ledapi__Config   *message,
                      uint8_t             *out);
size_t ledapi__config__pack_to_buffer
                     (const Ledapi__Config   *message,
                      ProtobufCBuffer     *buffer);
Ledapi__Config *
       ledapi__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledapi__config__free_unpacked
                     (Ledapi__Config *message,
                      ProtobufCAllocator *allocator);
/* Ledapi__FrameSet methods */
void   ledapi__frame_set__init
                     (Ledapi__FrameSet         *message);
size_t ledapi__frame_set__get_packed_size
                     (const Ledapi__FrameSet   *message);
size_t ledapi__frame_set__pack
                     (const Ledapi__FrameSet   *message,
                      uint8_t             *out);
size_t ledapi__frame_set__pack_to_buffer
                     (const Ledapi__FrameSet   *message,
                      ProtobufCBuffer     *buffer);
Ledapi__FrameSet *
       ledapi__frame_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledapi__frame_set__free_unpacked
                     (Ledapi__FrameSet *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ledapi__Frame_Closure)
                 (const Ledapi__Frame *message,
                  void *closure_data);
typedef void (*Ledapi__ClassicConfig_Closure)
                 (const Ledapi__ClassicConfig *message,
                  void *closure_data);
typedef void (*Ledapi__ScanConfig_Closure)
                 (const Ledapi__ScanConfig *message,
                  void *closure_data);
typedef void (*Ledapi__Config_Closure)
                 (const Ledapi__Config *message,
                  void *closure_data);
typedef void (*Ledapi__FrameSet_Closure)
                 (const Ledapi__FrameSet *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ledapi__frame__descriptor;
extern const ProtobufCMessageDescriptor ledapi__classic_config__descriptor;
extern const ProtobufCMessageDescriptor ledapi__scan_config__descriptor;
extern const ProtobufCEnumDescriptor    ledapi__scan_config__scan_mode__descriptor;
extern const ProtobufCEnumDescriptor    ledapi__scan_config__direction__descriptor;
extern const ProtobufCMessageDescriptor ledapi__config__descriptor;
extern const ProtobufCEnumDescriptor    ledapi__config__mode__descriptor;
extern const ProtobufCEnumDescriptor    ledapi__config__preset__descriptor;
extern const ProtobufCMessageDescriptor ledapi__frame_set__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_coapapi_2eproto__INCLUDED */
