/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: coapapi.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "coapapi.pb-c.h"
void   ledapi__frame__init
                     (Ledapi__Frame         *message)
{
  static const Ledapi__Frame init_value = LEDAPI__FRAME__INIT;
  *message = init_value;
}
size_t ledapi__frame__get_packed_size
                     (const Ledapi__Frame *message)
{
  assert(message->base.descriptor == &ledapi__frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ledapi__frame__pack
                     (const Ledapi__Frame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ledapi__frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ledapi__frame__pack_to_buffer
                     (const Ledapi__Frame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ledapi__frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ledapi__Frame *
       ledapi__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ledapi__Frame *)
     protobuf_c_message_unpack (&ledapi__frame__descriptor,
                                allocator, len, data);
}
void   ledapi__frame__free_unpacked
                     (Ledapi__Frame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ledapi__frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ledapi__config__init
                     (Ledapi__Config         *message)
{
  static const Ledapi__Config init_value = LEDAPI__CONFIG__INIT;
  *message = init_value;
}
size_t ledapi__config__get_packed_size
                     (const Ledapi__Config *message)
{
  assert(message->base.descriptor == &ledapi__config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ledapi__config__pack
                     (const Ledapi__Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ledapi__config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ledapi__config__pack_to_buffer
                     (const Ledapi__Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ledapi__config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ledapi__Config *
       ledapi__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ledapi__Config *)
     protobuf_c_message_unpack (&ledapi__config__descriptor,
                                allocator, len, data);
}
void   ledapi__config__free_unpacked
                     (Ledapi__Config *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ledapi__config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ledapi__frame_set__init
                     (Ledapi__FrameSet         *message)
{
  static const Ledapi__FrameSet init_value = LEDAPI__FRAME_SET__INIT;
  *message = init_value;
}
size_t ledapi__frame_set__get_packed_size
                     (const Ledapi__FrameSet *message)
{
  assert(message->base.descriptor == &ledapi__frame_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ledapi__frame_set__pack
                     (const Ledapi__FrameSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ledapi__frame_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ledapi__frame_set__pack_to_buffer
                     (const Ledapi__FrameSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ledapi__frame_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ledapi__FrameSet *
       ledapi__frame_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ledapi__FrameSet *)
     protobuf_c_message_unpack (&ledapi__frame_set__descriptor,
                                allocator, len, data);
}
void   ledapi__frame_set__free_unpacked
                     (Ledapi__FrameSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ledapi__frame_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ledapi__frame__field_descriptors[1] =
{
  {
    "frame_data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ledapi__Frame, frame_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ledapi__frame__field_indices_by_name[] = {
  0,   /* field[0] = frame_data */
};
static const ProtobufCIntRange ledapi__frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ledapi__frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ledapi.Frame",
  "Frame",
  "Ledapi__Frame",
  "ledapi",
  sizeof(Ledapi__Frame),
  1,
  ledapi__frame__field_descriptors,
  ledapi__frame__field_indices_by_name,
  1,  ledapi__frame__number_ranges,
  (ProtobufCMessageInit) ledapi__frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ledapi__config__mode__enum_values_by_number[3] =
{
  { "OFF", "LEDAPI__CONFIG__MODE__OFF", 0 },
  { "FIXED_FRAME", "LEDAPI__CONFIG__MODE__FIXED_FRAME", 1 },
  { "SWISH_RAINBOW", "LEDAPI__CONFIG__MODE__SWISH_RAINBOW", 2 },
};
static const ProtobufCIntRange ledapi__config__mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ledapi__config__mode__enum_values_by_name[3] =
{
  { "FIXED_FRAME", 1 },
  { "OFF", 0 },
  { "SWISH_RAINBOW", 2 },
};
const ProtobufCEnumDescriptor ledapi__config__mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ledapi.Config.Mode",
  "Mode",
  "Ledapi__Config__Mode",
  "ledapi",
  3,
  ledapi__config__mode__enum_values_by_number,
  3,
  ledapi__config__mode__enum_values_by_name,
  1,
  ledapi__config__mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ledapi__config__field_descriptors[2] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ledapi__Config, mode),
    &ledapi__config__mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixed_frame",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ledapi__Config, fixed_frame),
    &ledapi__frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ledapi__config__field_indices_by_name[] = {
  1,   /* field[1] = fixed_frame */
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange ledapi__config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ledapi__config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ledapi.Config",
  "Config",
  "Ledapi__Config",
  "ledapi",
  sizeof(Ledapi__Config),
  2,
  ledapi__config__field_descriptors,
  ledapi__config__field_indices_by_name,
  1,  ledapi__config__number_ranges,
  (ProtobufCMessageInit) ledapi__config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ledapi__frame_set__field_descriptors[1] =
{
  {
    "frames",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ledapi__FrameSet, n_frames),
    offsetof(Ledapi__FrameSet, frames),
    &ledapi__frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ledapi__frame_set__field_indices_by_name[] = {
  0,   /* field[0] = frames */
};
static const ProtobufCIntRange ledapi__frame_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ledapi__frame_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ledapi.FrameSet",
  "FrameSet",
  "Ledapi__FrameSet",
  "ledapi",
  sizeof(Ledapi__FrameSet),
  1,
  ledapi__frame_set__field_descriptors,
  ledapi__frame_set__field_indices_by_name,
  1,  ledapi__frame_set__number_ranges,
  (ProtobufCMessageInit) ledapi__frame_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
